name: Build Vite Application

on:
  workflow_call:
    inputs:
      build_ref:
        description: 'Git ref/branch to build'
        required: false
        default: 'main'
        type: string
    secrets:
      VITE_AUTH0_DOMAIN:
        required: true
      VITE_AUTH0_CLIENT_ID:
        required: true
      VITE_BRAND_TEXT:
        required: true
      VITE_BRAND_FAVICON:
        required: true
    outputs:
      artifact-id:
        description: 'ID of the uploaded artifact'
        value: ${{ jobs.build.outputs.artifact-id }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact-id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ inputs.build_ref }}

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        env:
          VITE_AUTH0_DOMAIN: ${{ secrets.VITE_AUTH0_DOMAIN }}
          VITE_AUTH0_CLIENT_ID: ${{ secrets.VITE_AUTH0_CLIENT_ID }}
          VITE_BRAND_TEXT: ${{ secrets.VITE_BRAND_TEXT }}
          VITE_BRAND_FAVICON: ${{ secrets.VITE_BRAND_FAVICON }}
        run: npm run build

      - name: Upload artifact
        id: upload
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./dist
